-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0vYonEcVAt3UAMRFoFzYeCD/5fY87A9HpuZ69mldPF+gCgYIKoZIzj0DAQehRANCAATurcyZMALGCoKRT+oWxhjFAK6bgeVcUEQpFAuY7s7k4td4GY8xgPmBnb4ROW5YICUBvPU5zamtGFmfrjzaxpVn
-----END PRIVATE KEY-----